spring:
  aop:
    proxyTargetClass: true
  application:
    name: api-gateway-zuul-1
  mvc:
    dispatch-options-request: true
    
    

server:
  port: 8765

eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

zuul:
  routes:
    resource-server-mvc-alarm: /resource-server-mvc-alarm/**      
    resource-server-mvc-2: /resource-server-mvc-2/**
    resource-server-mvc-cache-alarm: /resource-server-mvc-cache-alarm/**
    authorization-server-1:
      sensitiveHeaders: Authorization
      path: /authorization-server-1/**
      stripPrefix: false 
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 200
    max-per-route-connections: 20
    time-unit: MILLISECONDS
    time-to-live: 10000
  ignore-security-headers: true
    
ribbon:  
  eureka:
    enable: true
  isSecure: false
  ReadTimeout: 60000
  ConnectTimeout: 60000    
    
    
security:
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://localhost:8769/authorization-server-1/oauth/token
      userAuthorizationUri: /authorization-server-1/oauth/authorize
      clientId: fooClient
      clientSecret: fooSecret
    resource:
      jwt:
        keyValue: "abc"
      id: fooScope
      serviceId: ${PREFIX:}resource

logging:
  level.org.springframework.security: DEBUG



    
    
    
    